spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/outreachdb
  cloud:
    config:
      uri: http://localhost://8002/
logging:
  level:
    com.eventmgmt.eventservice: DEBUG
  pattern:
    console: %d{yyyy-MM-dd HH:mm:ss} - %msg%n